# This is the local dev database
# $ pnpm prisma migrate dev --name init

services:
  web:
    container_name: lol-web
    build:
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL_BUILD}
        RIOT_API_KEY: ${RIOT_API_KEY}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_PORT: ${MINIO_PORT}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIOT_API_KEY: ${RIOT_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      NEXT_TELEMETRY_DISABLED: '1'
    ports:
      - "9003:3000"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`lol.awot.dev`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    container_name: lol-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5432
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/share:/pgshare
      - ./db/scripts/:/pgscripts:ro
    ports:
      - "9004:5432"

  minio:
    image: minio/minio:latest
    container_name: lol-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9005:9005"
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9005"
