# This is the local dev database
# $ pnpm prisma migrate dev --name init

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        RIOT_API_KEY: ${RIOT_API_KEY}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_PORT: ${MINIO_PORT}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RIOT_API_KEY: ${RIOT_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      NEXT_TELEMETRY_DISABLED: '1'
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    container_name: lol-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdhjDHJsdchjnk12NKADHJNK23ASNK1
      PGPORT: 5432
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/share:/pgshare
      - ./db/scripts/:/pgscripts:ro
    ports:
      - "5432:5432"

  minio:
    image: minio/minio@latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9001"

